### ISSUE TITLE
Providers and Context

### ISSUE THREAD

**Issue by spencer516** [alexlafroscia/ember-provider#2]
@alexlafroscia — thank you for creating this! Literally six days ago I wrote a comment on an internal PR that mused about creating _something exactly like this_. 

But there was one additional specific piece that we were thinking about as well that I don't _think_ `ember-provider` has an answer for (yet!) — something along the lines of [React Context](https://reactjs.org/docs/context.html) where I can also create a _Consumer_ component some number of levels underneath the provider, so I can bypass passing state many many levels deep.

I have some thoughts about how to make something like that work in Ember-land, but wanted to see if you maybe were also exploring something along these lines before I went and implemented it. (Or if that is in the spirit of what you're hoping to accomplish with this add-on). 

I think theres some questions/constraints that would need to be considered around when it's safe to destroy the provider, how do know which instance of the provider is tied to which consumer, etc. If you'd like to explore this here, happy to contribute however I can. (Also happy to elaborate a little more _why_ we were thinking about this type of solution).

**Comment by alexlafroscia** [comment]
I've been exploring this a bit, too! React Context was a big inspiration for this addon (hense the name). I would love to come up with a pattern around that in Ember, even if it's a total deviation from the current approach.

> I have some thoughts about how to make something like that work in Ember-land,

I'd love to hear about this!

> but wanted to see if you maybe were also exploring something along these lines before I went and implemented it

I did have a thought alone those lines. I have a local branch playing with something like this:

```javascript
class Parent extends Component {
  @provider('something', { root: true })
  myProvider
}
```

```javascript
class Child extends Component {
  @provider('something')
  myProvider
}
```

where, if rendered like this:

```
<Parent>
  <Child />
</Parent>
```

`Child` receives the same instance that `Parent` already created, and they share that instance, rather than `Child` creating their own. Re-visiting the thought now, it makes more sense that `Child` would declare that it wants to share instead, but the API here is very much TBD (and the whole thing currently doesn't work. More explanation later).

How do you feel about sharing the injected service between them? Were you imagining something based more heavily on components and the template?

The reason I've been staying on the DI side of things is that I _really_ like that API in Ember and how easy it can make testing. Our application has also paid penalties for instantiating too many components, so avoiding that overhead is welcome in my opinion.

I guess, when comparing the approach I'm thinking here with that of React's Context, you end up with 

`Context.Provider` -> inject a shared object
`Context.Consumer` -> whoever does the injecting

You don't _need_ a component for either of those things, because we have other abstractions that are well-suited to the "pass state around without passing props" task.

We totally could introduce something like this, on top of the mechanics that I described earlier, if you want to opt into the declarative API:

```handlebars
<Parent>
  <Consumer @provider="something" as |sharedProviderObject|>
    <SomeComponentThatNeedsTheState @prop={{sharedProviderObject.whatever}} />
  </Consumer>
</Parent>
```

The problem I've run into with my proposed API, conceptually, is that you need to discover whether a parent component has already created a provider and grab that instance, based on rendering order. Ember doesn't really have any "good ways" of doing this that I've found, at least. Maybe something based on React's new Hooks API could be done, though -- based on order of execution, know which parent provider you should be given.

Would love to hear your thoughts!

**Comment by spencer516** [comment]
> The problem I've run into with my proposed API, conceptually, is that you need to discover whether a parent component has already created a provider and grab that instance, based on rendering order. 

Yes — I think that's a really hard problem to solve without some context/state passed down. But maybe that's _okay_. 

If we assume that the base use case is that there will only ever be one instance of a given Provider at a time, then we can just make sure that the provider is destroyed when it is no longer used by any components (your existing `inject.ts` is like 90% of the way to that already). 

But, when we want to break that assumption, then you could introduce an optional dependent key (maybe similar in concept to the `key` property of the `each` helper). 

So — in that world, if we had these components and templates:

```js
class ThingA extends Component {
  @provider('load-data')
  loadData;
}

class ThingB extends Component {
  @provider('load-data', 'key')
  loadData;

  key = 'scope1';
}

class ThingC extends Component {
  @provider('load-data')
  loadData;
}
```

```hbs
<ThingA />
<ThingB />
<ThingB @key="scope2" />
<ThingC />
```

I would expect that there are _three_ instances of the Provider — one for the two instances of `ThingA` and `ThingB`, and one for each of the "scopes" in `ThingB` (`'scope1'` & `'scope2'`).

**Comment by alexlafroscia** [comment]
> If we assume that the base use case is that there will only ever be one instance of a given Provider at a time

I'm not sure that's a good assumption to make here -- if that _was_ the behavior, how would it differ from a Service?

I think your scope idea is pretty neat! Explicitly describing the "scope" of how to share a provider is a really interested approach.

Can you check out the PR that I opened and let me know what you think? There are API examples in the tests cases. I mean for that to be a strawman more than anything else so we can talk more about what the API for this might look like and some of the challenges that I've run into.

One part of my PR, that I didn't think about until looking at your examples here, is that I am banking on some kind of ancestor relationship between the "owner" of the provider and those that are receiving it. For example, in a case like this:

```hbs
<Parent>
  <Child />
  <Child />
</Parent>
```

there is only _one_ instance of the Provider (assuming that the `Child` component opts into sharing with the parent) but in this case:

```hbs
<Child />
<Child />
```

There are two instances (because my current implementation creates one if the parent didn't provide. That behavior is 100% up for discussion).

**Comment by spencer516** [comment]
> I'm not sure that's a good assumption to make here -- if that was the behavior, how would it differ from a Service?

It'd be different in two ways, in this case I suppose — a Provider is not a singleton and it's lifecycle is bound to the components that depend on it. Almost as if this just became a "weakly held service"...it only exists as long as there are things that depend on it. But, maybe that doesn't end up adding a ton of value. 

And I'll take a look at your PR!

**Comment by spencer516** [comment]
Resolved by https://github.com/alexlafroscia/ember-provider/pull/4
